import os

env = Environment(ENV = os.environ,
                  CPPPATH = ['#'],
                  LIBPATH = ['#'],
                  LIBS = ['corona', 'cppunit', 'png', 'jpeg'])
env.Program(target = 'CoronaTest', source = 'CoronaTest.cpp')
