Import("base_env CORONA_LIBS");

env = base_env.Copy()
env.Append(CPPPATH = ['#src'],
           LIBPATH = ['#src'],
           LIBS = CORONA_LIBS + ['gdi32', 'comdlg32', 'comctl32'])
Tool('mingw')(env)
res = env.RES('winviewer.res.o', 'winviewer.rc')
env.Program('winviewer', ['winviewer.cpp', res])
