import os
from os import path

Import('env')

gifdir = 'libungif-4.1.0'

SOURCES = [
    'Corona.cpp',
    'Debug.cpp',
    'DefaultFileSystem.cpp',
    'OpenBMP.cpp',
    'OpenGIF.cpp',
    'OpenJPEG.cpp',
    'OpenPCX.cpp',
    'OpenPNG.cpp',
    'OpenTGA.cpp',
    'SavePNG.cpp',
] + map(lambda n: gifdir + '/' + n, SConscript(dirs = gifdir))

env2 = env.Copy(CPPPATH = gifdir)

env2.Library(target = 'corona', source = SOURCES)
