import os
from os import path

Import('env')

SOURCES = [
    'Corona.cpp',
    'Debug.cpp',
    'DefaultFileSystem.cpp',
    'OpenBMP.cpp',
    'OpenJPEG.cpp',
    'OpenPCX.cpp',
    'OpenPNG.cpp',
    'OpenTGA.cpp',
    'SavePNG.cpp',
]

env.Library(target = 'corona', source = SOURCES)
